export const PAPRIKA_MEALS = [
  {
    "name": "Asian Sriracha Noodles",
    "ingredients": [
      "2 bricks of the squiggly knife-cut style noodles (half a pack)",
      "1 block of sriracha tofu, cubed",
      "1 pack of vegetables with stir-fry sauce"
    ],
    "directions": [
      "Heat a medium pot and cook noodles according to package instructions.",
      "Add your vegetables and tofu in a large skillet and cook for about 5 minutes.",
      "Add in the stir-fry sauce and cook for another 2 minutes. Add in the cooked noodles and the sesame and soy sauce packet that came with the noodles.",
      "Mix through and serve!"
    ],
    "notes": "Source: Instagram.com",
    "link": "https://www.instagram.com/reel/C90ksl-SBeO/?igsh=MWQ1Z2FlbXlmb2xjZg%3D%3D",
    "category": "",
    "imageUrl": "https://scontent-msp1-1.cdninstagram.com/v/t51.29350-15/452633096_1403272011075597_2398284088503447884_n.jpg?stp=dst-jpg_e15&_nc_ht=scontent-msp1-1.cdninstagram.com&_nc_cat=109&_nc_ohc=jh-Cq79EC7sQ7kNvgHHkjNY&_nc_gid=59dfd7a8ac574f669336ba0acba70dea&edm=ANTKIIoBAAAA&ccb=7-5&oh=00_AYAUKnV5VL_G4mlEsiuHfqluMEceBnB8kzx_Le8eUknOEQ&oe=671D92AA&_nc_sid=d885a2",
    "isFavorite": false,
    "rating": 4,
    "cookCount": 0
  },
  {
    "name": "High Protein Lazy Dinner",
    "ingredients": [
      "jalape\u00f1o crema:",
      "3/4 cup plain vegan yogurt",
      "1/2 tbsp olive oil",
      "1 clove garlic",
      "1/2 of a jalape\u00f1o",
      "1/2 cup cilantro",
      "1/2 of a lime, juiced",
      "salt & pepper to taste"
    ],
    "directions": [
      "recipe:",
      "+ 1 bag of the spicy Mexican style riced cauliflower from Trader Joe\u2019s",
      "+ protein of choice (i did both black beans and vegan chorizo but any protein will work!)",
      "+ optional toppings: cheese, lettuce, green onion, cilantro, tortilla chips"
    ],
    "notes": "Source: Instagram.com",
    "link": "https://www.instagram.com/reel/C_3F0UgJrpx/?igsh=OHJnNGloMzZxbGYz",
    "category": "",
    "imageUrl": "https://scontent-msp1-1.cdninstagram.com/v/t51.29350-15/459107127_1212049890032570_80105956222102147_n.jpg?stp=dst-jpg_e35_p1080x1080_sh0.08&_nc_ht=scontent-msp1-1.cdninstagram.com&_nc_cat=102&_nc_ohc=HFeQ_aPW9ykQ7kNvgE9jG6k&_nc_gid=2d0fc56a27a64d61affd891702de3d2b&edm=ANTKIIoBAAAA&ccb=7-5&oh=00_AYCad-IiNrLp6tmQZ8k8HYEI_YQATIhUyt5cjFFJ2SLXmQ&oe=671D8FAF&_nc_sid=d885a2",
    "isFavorite": false,
    "rating": 5,
    "cookCount": 0
  },
  {
    "name": "Broccoli Caesar Pasta",
    "ingredients": [
      "12 oz fresh broccoli florets",
      "1 bottle of vegan Caesar dressing",
      "Dairy-free parmesan",
      "16 oz pasta of choice",
      "\u00bd cup reserved pasta water",
      "Rosemary croissant croutons, crumbled on top",
      "Salt & pepper, to taste"
    ],
    "directions": [
      "Preheat your oven to 425 degrees.",
      "Add the broccoli florets to a large bowl, half the bottle of dressing, and a handful of parmesan. Mix until combined and then transfer to a baking dish and bake for 15 minutes or until the broccoli starts to brown.",
      "Bring a large pot of salted water to a boil as the broccoli bakes, add the pasta, and cook according to packaging instructions. Once the pasta is finished cooking, reserve \u00bd cup of the pasta water.",
      "Drain the pasta and transfer it to a large bowl. Add in the cooked broccoli, the other half of the dressing, and more parmesan to taste. Mix until combined.",
      "Top with crumbled croutons when serving, and enjoy!"
    ],
    "notes": "Source: Instagram.com",
    "link": "https://www.instagram.com/reel/DEDZn4CyUua/?igsh=MTcxbzJ1Mm0zNTNtaQ%3D%3D",
    "category": "Pasta",
    "imageUrl": "https://instagram.fmli1-1.fna.fbcdn.net/v/t51.2885-15/471866251_18483950872043998_7576822468564366684_n.jpg?stp=dst-jpg_e15_tt6&_nc_ht=instagram.fmli1-1.fna.fbcdn.net&_nc_cat=110&_nc_ohc=Xg3lU8G9K_cQ7kNvgFCqhs9&_nc_gid=72dfd977da754268a55e9f2877ea6c28&edm=APU89FABAAAA&ccb=7-5&oh=00_AYC8EqyylfCHXZffOgjFZWdfzBm6KYVv_yZcvPLl9Dp9kw&oe=678B67CF&_nc_sid=bc0c2c",
    "isFavorite": false,
    "rating": 0,
    "cookCount": 0
  },
  {
    "name": "Bread Boat Parm",
    "ingredients": [
      "2 Sourdough Boules",
      "2-3 Tbsp Dairy-Free Boursin Cheese Spread",
      "6-10 Impossible Nuggets",
      "1 Package of Roasted Vegetables Dressed with Garlic and Herbs",
      "\u00bd-\u00be Cup Tomato Basil Marinara",
      "Dairy-free Mozzarella and Parm Blend"
    ],
    "directions": [
      "Preheat your oven to 400 degrees.",
      "Prepare your bread bowls by hollowing out the top and removing some of the filling, making sure it's not too thin around the edges.",
      "Coat the inside of each bread bowl with the dairy-free boursin cheese and pop them in the oven to bake for about 4-6 minutes.",
      "As the bread bakes, prepare the impossible nuggets and roasted vegetables according to package instructions.",
      "Dice the nuggets into quarters and add them to the bowl with the vegetables and marinara sauce. Mix until fully combined.",
      "Top with a large handful of the dairy-free cheese blend and pop back into the oven for another 10-15 minutes or until the cheese is melted.",
      "Garnish with fresh parsley and dig in!"
    ],
    "notes": "",
    "link": "",
    "category": "Dinner",
    "imageUrl": "",
    "isFavorite": false,
    "rating": 0,
    "cookCount": 0
  },
  {
    "name": "Cauliflower Fajitas",
    "ingredients": [
      "Here\u2019s what you\u2019ll need:",
      "Spice Mix: 2 tablespoons chili powder (I use a regular for my family but you can do a mild or less for spice preference), 1 teaspoon paprika, 1 teaspoon oregano, 3/4 teaspoon salt, 1 teaspoon onion powder, 1 teaspoon garlic powder",
      "1 head cauliflower, chopped into bite-size florets",
      "3 bell peppers, thinly sliced",
      "1 large onion, thinly sliced"
    ],
    "directions": [
      "1\ufe0f\u20e3 Toss together the cauliflower with oil and half the spice mix until well coated.",
      "2\ufe0f\u20e3 Toss the peppers and onions with oil and remaining spice mix.",
      "3\ufe0f\u20e3 Place in a single layer on a baking sheet (I use one for the cauliflower and one for the peppers and onions) and cook at 400 degrees F for Roast for 30-35 minutes, until the vegetables are tender and slightly caramelized, stirring halfway through.",
      "I like to check the vegetables about 20 minutes in, stirring the vegetables and tasting, adding more salt as needed or a little more oil if the vegetables seem dry.",
      "4\ufe0f\u20e3 Serve in warmed tortillas. I usually serve alongside black beans and guacamole! \ud83e\udd51"
    ],
    "notes": "Source: Instagram.com",
    "link": "https://www.instagram.com/reel/DIt_c6eTF2P/?igsh=MXEwbGJyeTdiOWVkOA%3D%3D",
    "category": "",
    "imageUrl": "https://scontent.cdninstagram.com/v/t51.75761-15/491516236_18309500338229981_3789554744264995765_n.jpg?stp=cmp1_dst-jpg_e35_s640x640_tt6&_nc_cat=102&ccb=7-5&_nc_sid=18de74&_nc_ohc=cR435mGYlOwQ7kNvwEYTkSu&_nc_oc=Adkr7Fde3ZAfNjgORpWpWu_TRiXvSzsnZ3fFS8X3bhbRSI3HHLwq88hDH4ZbV60z75Y&_nc_zt=23&_nc_ht=scontent.cdninstagram.com&_nc_gid=-ljPQzT86jUnJSDx_2HyXg&oh=00_AfIaJAc6zsDGaVABFvXo7M7IowsR8VktVb53gvPmZsN13w&oe=682997F6",
    "isFavorite": false,
    "rating": 0,
    "cookCount": 0
  },
  {
    "name": "Cheesy Pea and Bacon Pasta",
    "ingredients": [
      "Ingredients (serves 2-3)",
      "300g extra firm tofu",
      "2 tbsp tamari or soy sauce",
      "1 tbsp extra virgin olive oil",
      "1/2 tbsp maple syrup",
      "2 tsp smoked paprika",
      "1 tsp garlic powder",
      "2 tbsp cornstarch",
      "4 cloves of crushed garlic",
      "200g frozen peas",
      "200g dried pasta of choice, cooked",
      "1 tbsp white miso paste",
      "80-100ml (one ladle) salty pasta water",
      "3 tbsp nutritional yeast"
    ],
    "directions": [],
    "notes": "Source: Instagram.com",
    "link": "https://www.instagram.com/reel/DEktQMsIDOt/?igsh=Z3hwOTJwNXNwd2N1",
    "category": "",
    "imageUrl": "https://instagram.fmli1-1.fna.fbcdn.net/v/t51.2885-15/472488857_18044457395336427_2992014084001596447_n.jpg?stp=dst-jpg_e15_tt6&efg=eyJ2ZW5jb2RlX3RhZyI6ImltYWdlX3VybGdlbi4xMTY4eDIwNzIuc2RyLmY3NTc2MS5kZWZhdWx0X2NvdmVyX2ZyYW1lIn0&_nc_ht=instagram.fmli1-1.fna.fbcdn.net&_nc_cat=103&_nc_oc=Q6cZ2QFRoJN7YsYN2hv_wkrFvHr6QQl9Ka7B7X27EYDkX6tQa0CvtRDUF_C-jh7jMtEp_R4&_nc_ohc=O8h6W7yXRosQ7kNvgFSzZob&_nc_gid=yIAshr-V5kYj_T41e2t7jg&edm=APs17CUBAAAA&ccb=7-5&ig_cache_key=MzU0MTE1NDIzMjI0OTg4OTcwOQ%3D%3D.3-ccb7-5&oh=00_AYFnrCOTXCWCo5Vd96skaC5AQoWJv7ObUKt-a1loSiGtgA&oe=67E64460&_nc_sid=10d13b",
    "isFavorite": false,
    "rating": 0,
    "cookCount": 0
  },
  {
    "name": "Cheesy Veggie Orzo Risotto",
    "ingredients": [
      "2/3 cup soaked or flash-soaked cashews",
      "2 tablespoons white miso",
      "1/4 cup nutritional yeast",
      "2 cups vegetable stock",
      "1 cup edamame",
      "1 cup frozen broccoli",
      "1 cup frozen cauliflower rice",
      "Cook another 5\u20137 minutes until the veggies are tender and the mixture is thick and creamy.",
      "1 tbsp olive oil",
      "1 shallot diced",
      "3 cloves garlic minced",
      "16 oz whole grain orzo",
      "7 cups vegetable stock divided",
      "2/3 cup cashews soaked for 1 hour or \"flash soaked\"",
      "1 tbsp white miso*",
      "1/4 cup nutritional yeast",
      "1 cup frozen edamame",
      "1 cup frozen riced cauliflower",
      "1 cup broccoli chopped"
    ],
    "directions": [
      "In a large pot, heat 1 tablespoon olive oil. Saut\u00e9 1 diced shallot and 3 minced garlic cloves for 1\u20132 minutes.",
      "Add 16 oz orzo and toast for about 1 minute.",
      "Pour in 5 cups of vegetable stock, bring to a boil, then reduce to a strong simmer. Cook for 8\u201310 minutes, stirring often.",
      "While the orzo cooks, blend together:",
      "Blend until smooth and creamy.",
      "Stir the cashew mixture into the orzo, along with:",
      "Pro Tips",
      "Flash soak cashews by covering them in boiling water for 10\u201315 minutes if you\u2019re short on time.",
      "If you want to boost the veggie count even more, stir in spinach or peas at the end.",
      "Leftovers reheat beautifully for lunchboxes or next-day meals.",
      "In a large pot, heat olive oil over medium heat. Add shallot and garlic. Cook for 1-2 minutes.",
      "Add orzo and toast for about 1 minute.",
      "Add 5 cups vegetable stock and bring to a boil. Then reduce heat to a strong simmer for about 8-10 minutes, stirring frequently to prevent orzo from sticking.",
      "While pasta cooks, in a high-powered blender puree cashews, miso, nutritional yeast, and remaining 2 cups of vegetable stock until smooth.",
      "Once orzo has absorbed most of the liquid and is al dente, stir in the cashew mixture, edamame, broccoli, and cauliflower rice. Continue to simmer until veggies have defrosted, most of the liquid is absorbed, and you\u2019re left with a creamy consistency (about 5-7 minutes).",
      "Enjoy right away or save the rest for lunchboxes!"
    ],
    "notes": "*Can sub miso for vegetable bullion.\nServings: Servings: 8 | Prep: 10 minutes | Cook: 20 minutes | Source: Plantbasedjuniors.com",
    "link": "https://plantbasedjuniors.com/cheesy-veggie-orzo-risotto/",
    "category": "",
    "imageUrl": "https://plantbasedjuniors.com/wp-content/uploads/2025/05/DSC00070-2-scaled.jpg",
    "isFavorite": false,
    "rating": 0,
    "cookCount": 0
  },
  {
    "name": "Chipotle Black Bean Dump & Bake Casserole",
    "ingredients": [
      "FOR THE BROTH:",
      "1 1/2 cups low-sodium vegetable broth (homemade or store-bought)",
      "1 14 ounce can diced tomatoes in tomato juice",
      "2 chipotle peppers in adobo finely chopped*",
      "1 teaspoon ground cumin",
      "1 teaspoon garlic powder",
      "FOR THE CASSEROLE:",
      "1 sweet potato peeled and diced (227g or 1 1/2 cups)",
      "1 red bell pepper diced",
      "1/2 red onion diced",
      "2 15 ounce cans black beans drained and rinsed; about 2 3/4 cups",
      "1/2 bunch cilantro leaves and stems divided and chopped",
      "1 cup dry brown rice",
      "Chipotle Mayo (optional, for topping)",
      "Avocado (optional, for topping)"
    ],
    "directions": [
      "Prep: Preheat the oven to 400F. Whisk the vegetable broth, tomatoes, chipotle peppers, cumin, and garlic powder together in a medium pot; cover and bring to a boil over high heat.",
      "Dry Ingredients: While the liquid is heating up, add the sweet potato, bell pepper, onion, black beans, and cilantro stems to a 9\u00d713\u2033 pan or casserole dish and mix well. Sprinkle the brown rice evenly over the top.",
      "Bake: Pour the boiling liquid over the casserole, and gently mix everything together to make sure the rice is submerged. Cover the casserole with aluminum foil (or parchment paper, followed by aluminum foil) and bake in the middle rack of the oven for 60 minutes.",
      "Serve & Store: Remove from the oven and top with the fresh cilantro leaves and diced avocado and chipotle mayo (or as desired). Refrigerate leftovers in a sealed container for up to one week, or in the freezer for up to one month."
    ],
    "notes": "Reduce the chipotle peppers to only 1 if you are sensitive to heat\n\nWhite Rice: Use 1 cup of white rice instead of brown. Follow the recipe as written, but bake at 375F for only 45 minutes.\n\nQuinoa: Use 1 cup of quinoa instead of brown. Follow the recipe as written, but bake at 375F for only 35 minutes.\n\nThis recipe is a variation of and inspired by my Southwestern Black Bean Casserole, but Jackie of Vegan Yack Attack also has a delicious Chipotle Brown Rice Bake as well!\nPrep: 15 minutes | Cook: 1 hour | Source: Frommybowl.com",
    "link": "https://frommybowl.com/chipotle-black-bean-dump-bake-casserole/",
    "category": "Casseroles",
    "imageUrl": "https://frommybowl.com/wp-content/uploads/2022/12/Chipotle_Black_Bean_Casserole_Vegan_FromMyBowl-400x600.jpg",
    "isFavorite": false,
    "rating": 0,
    "cookCount": 0
  },
  {
    "name": "Chris \u2022 \u24cb | Creamy Spinach and Artichoke Pasta Ready in Just 10 Minutes! Welcome",
    "ingredients": [
      "16 oz Organic Lemon Torchiette Pasta (If the lemon pasta isn\u2019t available, any other variety works great)",
      "12 oz Marinated Artichoke Hearts",
      "16 oz Frozen Organic Spinach",
      "6 oz Boursin Dairy-Free Cheese Spread",
      "1 Package (6) Babybel Cheese\u2019s",
      "Green Goddess Seasoning, to taste"
    ],
    "directions": [
      "Cook the pasta according to package instructions. As that cooks, add the marinated artichokes and frozen spinach to a large skillet over medium heat and cook for 2-3 minutes. Add in the Boursin cheese spread and Babybel cheese and mix well. Cook until fully melted for about 3-4 minutes. Season with Green Goddess Seasoning to taste. Drain the pasta and combine the sauce and pasta together. Mix well and enjoy!"
    ],
    "notes": "Source: Instagram.com",
    "link": "https://www.instagram.com/reel/DBO8F1hyrnw/?igsh=MWx5OGdxNzE1c205cA%3D%3D",
    "category": "Pasta",
    "imageUrl": "https://scontent-sjc3-1.cdninstagram.com/v/t51.29350-15/463016183_540593708584552_3942724983703078392_n.jpg?stp=dst-jpg_e15&_nc_ht=scontent-sjc3-1.cdninstagram.com&_nc_cat=104&_nc_ohc=Symt7z8nS_oQ7kNvgG_I0v_&_nc_gid=2f1bce78fef54f54944d54d58d901913&edm=ANTKIIoBAAAA&ccb=7-5&oh=00_AYBY9_enstsJPzpKBMatMwTmj0yavx0d6UOUz5Zg27zYPw&oe=67269200&_nc_sid=d885a2",
    "isFavorite": false,
    "rating": 0,
    "cookCount": 0
  },
  {
    "name": "Creamy Pesto Gnocchi",
    "ingredients": [
      "Basil Pesto",
      "1/4 cup pine nuts or cashews",
      "2 cups fresh packed basil",
      "2 cloves garlic",
      "3 tablespoons fresh lemon juice",
      "1/4 cup nutritional yeast",
      "1/2 teaspoon salt",
      "6 tablespoons olive oil",
      "The Rest",
      "1 pound uncooked gnocchi",
      "13.5 ounce can full fat coconut milk",
      "1/4 cup dry white wine I used sauvignon blanc",
      "salt + black pepper, to taste",
      "3 cups baby spinach",
      "Vegan Parmesan optional"
    ],
    "directions": [
      "Make the pesto",
      "Place all ingredients except the olive oil in a food processor and process until finely chopped.",
      "With the food processor running, slowly drizzle in the olive oil. Process until smooth (there will still be a little texture, but mostly smooth), adding a little more olive oil or water if needed to help it blend.",
      "Set aside while you prepare the gnocchi.",
      "Pesto Gnocchi",
      "In a large deep skillet or pot, add 1/2 cup pesto (use the leftovers elsewhere), coconut milk and wine. Stir and warm over medium heat.",
      "When the sauce starts to simmer, add the gnocchi and give it a good stir.",
      "Bring to a boil, then lower heat to a simmer and cook, uncovered for 5 minutes, stirring occasionally.",
      "The sauce will thicken as the gnocchi cooks, so add a little water if needed. Add salt + pepper, to taste and stir in the spinach. Cook for another 1-2 minutes until the spinach has wilted.",
      "Test the gnocchi- at this point, it should be softened but not mushy. Cook an additional minute or two if needed.",
      "Serve immediately with a sprinkle vegan parmesan cheese and enjoy!"
    ],
    "notes": "Leftover gnocchi will keep for 2-3 days in the refrigerator. Add a little water to thin the sauce when you reheat it, as it will thicken. It can also be frozen, though it\u2019s better fresh.\n\nMay also add in sun dried tomatoes, halved cherry tomatoes, some tempeh or tofu bacon pieces or even Vegan Chicken for protein.\nServings: Servings: 6 servings | Prep: 10 mins | Cook: 8 mins | Source: noracooks.com",
    "link": "https://www.noracooks.com/creamy-pesto-gnocchi/?ck_subscriber_id=1404156537&utm_source=convertkit&utm_medium=email&utm_campaign=Vegan%20French%20Onion%20Soup,%20Pesto%20Gnocchi,%20Black%20Pepper%20Tofu!%20-%2016476750#wprm-recipe-container-14412",
    "category": "Dinner",
    "imageUrl": "https://www.noracooks.com/wp-content/uploads/2021/06/144A5148-150x225.jpg",
    "isFavorite": false,
    "rating": 0,
    "cookCount": 0
  },
  {
    "name": "Dumpling veggie stir fry",
    "ingredients": [
      "1/2 onion diced",
      "4 oz sliced mushrooms",
      "2 carrots julienned",
      "Splash of veggie broth for sauteing",
      "1 package tempeh cubed",
      "1 zucchini sliced",
      "2 cups broccoli florets",
      "3 tbsp teriyaki sauce (or soyaki) mixed with 1/4 cup water or broth",
      "1 package of dunplings (pot stickers)",
      "Sesame seeds and kimchi for serving"
    ],
    "directions": [
      "Add frozen broccoli and bell pepper to oan. When defrosted and starting to cook add the zucchini and any additional veggies.",
      "While veggies are cooking microwave dumpings for about 3 minutes.",
      "When veggies almost done cooking add tempeh and the sauce. Lastly add dumplings and heat through."
    ],
    "notes": "",
    "link": "https://youtu.be/xah3Pf0nqMw?si=dfqfGoSPtIVd-klO",
    "category": "Dinner",
    "imageUrl": "https://img.youtube.com/vi/xah3Pf0nqMw/hqdefault.jpg",
    "isFavorite": false,
    "rating": 0,
    "cookCount": 0
  },
  {
    "name": "Egg Bake",
    "ingredients": [],
    "directions": [
      "\u25aa\ufe0fPreheat oven to 200c",
      "\u25aa\ufe0fBoil your potatoes until soft",
      "\u25aa\ufe0fPrepare your 9 inch dish. Add potatoes to the dish and smash them so you sore as and cover the dish",
      "\u25aa\ufe0fDrizzle some oil over the potatoes and season with salt and pepper",
      "\u25aa\ufe0fAdd the spinach, pepper and tomatoes",
      "\u25aa\ufe0fMix the eggs with the milk and pour the mixture over the vegetables.",
      "\u25aa\ufe0fTop with cheese and bake for 25-30 minutes"
    ],
    "notes": "Source: Instagram.com",
    "link": "https://www.instagram.com/reel/DGbc6wwOvng/?igsh=NTNiOW96bHgxbWpv",
    "category": "",
    "imageUrl": "https://instagram.fmli1-1.fna.fbcdn.net/v/t51.2885-15/480919542_18263290849274350_7955219054872986511_n.jpg?stp=dst-jpg_e15_tt6&efg=eyJ2ZW5jb2RlX3RhZyI6IkNMSVBTLmltYWdlX3VybGdlbi4zMDAweDUzMjguc2RyLmY3NTc2MS5kZWZhdWx0X2NvdmVyX2ZyYW1lIn0&_nc_ht=instagram.fmli1-1.fna.fbcdn.net&_nc_cat=1&_nc_oc=Q6cZ2QGH_AIX-kjT4f-t7Ng7YYGLLk8kw8tMHKUillnkTMvkCFEizOil2Tt-qw_8SzG7Kr0&_nc_ohc=dhxnLKz3GG8Q7kNvgGi-b4W&_nc_gid=IBpePRezyVDyQvZ2Zf8_Uw&edm=APs17CUBAAAA&ccb=7-5&ig_cache_key=MzU3NDU3NzkxMjYyOTM2MTEyMA%3D%3D.3-ccb7-5&oh=00_AYHtUAMFCIj7Ottcy5GkDWVHgZAVGtpsivPXVNmN00FW1Q&oe=67EE315F&_nc_sid=10d13b",
    "isFavorite": false,
    "rating": 0,
    "cookCount": 0
  },
  {
    "name": "Instant Pot Oatmeal",
    "ingredients": [],
    "directions": [
      "1\ufe0f\u20e3 Place 1 can light coconut milk, 1 cup water, 1 cup uncooked steel cut oats, 1/2 tsp. Cinnamon, 1 tsp. Vanilla, 1/8 tsp. nutmeg in an Instant Pot.",
      "2\ufe0f\u20e3 Add the lid, turn handle to sealing and cook for 7 minutes at high pressure. Let come down naturally for 10 minutes, then quick release to remove any other pressure.",
      "3\ufe0f\u20e3 Open and stir! Enjoy as is, or with berries and/or a little sweetener if ya need it! \ud83c\udf53",
      "4\ufe0f\u20e3 PS- you can make this in the stove! Add all ingredients to a saucepan and bring to a boil; reduce heat to low and simmer until creamy, about 25 minutes."
    ],
    "notes": "Source: Instagram.com",
    "link": "https://www.instagram.com/p/B8SFcAOJIWH/?igsh=MWNid2M1ZGwwb2tkag%3D%3D",
    "category": "Breakfast",
    "imageUrl": "https://scontent.cdninstagram.com/v/t51.2885-15/83761041_173733400593938_9181903403656829239_n.jpg?stp=c216.0.648.648a_dst-jpg_e35_s640x640_tt6&_nc_cat=107&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiRkVFRC5iZXN0X2ltYWdlX3VybGdlbi5DMiJ9&_nc_ohc=u3UAipyvGqUQ7kNvwEjJUWH&_nc_oc=AdlWMglgRIWNSqEIqDqA8OP9jvKUeq7C1CytHbJttSTjKUp24UTwrwbFG3subvupj-0&_nc_zt=23&_nc_ht=scontent.cdninstagram.com&oh=00_AfiMq9nlSjgptyAKCLZNYXhlvyJifFp16_GwT7_CRIIs_Q&oe=692D824A",
    "isFavorite": false,
    "rating": 0,
    "cookCount": 0
  },
  {
    "name": "Lasagna Soup",
    "ingredients": [
      "1 package vegan meatballs, chopped, or ground beef",
      "1/3 cup (80 ml) water",
      "1 white onion diced",
      "3 cloves garlic minced",
      "1 (24 oz [680 g]) jar vegan marinara sauce",
      "1 (14.5 oz [411 g]) can petite diced tomatoes",
      "1 (28 oz) can tomato pur\u00e9e",
      "6 cups (1.44 L) water",
      "1 1/2 cups (150 g) dry campanelle pasta (or lasagna noodles broken up)",
      "For topping:",
      "Vegan ricotta",
      "Vegan parmesan cheese"
    ],
    "directions": [
      "Saute onion, garlic, and ground beef ,(meatballs). Once cooked add all other ingredients - EXCEPT noodles and bring to boil. Once boiling add noodles and cook until noodles are done.",
      "Serve with a dollop of vegan ricotta and a sprinkle of vegan parmesan, if desired."
    ],
    "notes": "Can be made quickly on the stovetop.\nServings: 8 people | Prep: 5 mins | Cook: 6 hrs | Source: sixvegansisters.com",
    "link": "https://www.sixvegansisters.com/2021/12/23/slow-cooker-lasagna-soup/",
    "category": "Dinner",
    "imageUrl": "https://i2.wp.com/www.sixvegansisters.com/wp-content/uploads/2021/12/IMG_2627-scaled.jpeg?fit=1920%2C2560&ssl=1",
    "isFavorite": false,
    "rating": 5,
    "cookCount": 0
  },
  {
    "name": "Mexican Corn Dip",
    "ingredients": [
      "1 can Mexican corn, drained",
      "1 can black beans, rinsed and drained",
      "1 can diced green chilis",
      "1/4 c. diced red bell pepper",
      "1 tsp. onion powder (or 1/4 chopped onion)",
      "1/2 c. mayo (choice \u2013 I used mayo with olive oil)",
      "1/2 c. sour cream (choice \u2013 I used light sour cream)",
      "1 to 1 1/2 cups shredded cheddar cheese",
      "Mexican Corn Dip",
      "1 can Mexican corn, drained",
      "1 can black beans, rinsed and drained",
      "1 can diced green chilis",
      "1/4 c. diced red bell pepper",
      "1 tsp. onion powder (or 1/4 chopped onion)",
      "1/2 c. mayo (choice \u2013 I used mayo with olive oil)",
      "1/2 c. sour cream (choice \u2013 I used light sour cream)",
      "1 to 1 1/2 cups shredded cheddar cheese",
      "Serve with Fritos corn chips and/or tortilla chips",
      "Rustic Honey"
    ],
    "directions": [
      "Serve with Fritos corn chips and/or tortilla chips",
      "Combine corn, chilis, red pepper and beans in a bowl.",
      "Give \u2019em a toss.",
      "Season with onion powder (if omitting chopped onion).",
      "Add the sour cream and mayo. Stir to combine. 5. Add in the cheese and fold into the dip.",
      "Serve with tortilla chips and Fritos scoops.",
      "CAUTION: This recipe grows and will make a large batch! I doubled the recipe for a big party and ended up with a huge amount of dip!",
      "Great recipe for a crowd! It gets many compliments!",
      "Combine corn, chilis, red pepper and beans in a bowl. Give \u2019em a toss.",
      "Season with onion powder (if omitting chopped onion).",
      "Add the sour cream and mayo. Stir to combine.",
      "Add in the cheese and fold into the dip.",
      "Serve with tortilla chips and Fritos scoops."
    ],
    "notes": "CAUTION: This recipe grows and will make a large batch! I doubled the recipe for a big party and ended up with a huge amount of dip!\n\nEnjoy!\nServings: Serves: 15-20 | Prep: 5 mins | Cook: 5 mins | Source: Rustichoney.com",
    "link": "https://rustichoney.com/mexican-corn-dip/",
    "category": "Tailgate",
    "imageUrl": "https://i0.wp.com/rustichoney.com/wp-content/uploads/2013/07/img_19691.jpg?w=2000&ssl=1",
    "isFavorite": false,
    "rating": 0,
    "cookCount": 0
  },
  {
    "name": "Mushroom Parm Sandwiches",
    "ingredients": [
      "Crispy Battered Shiitake Mushrooms",
      "Demi Baguette",
      "Garlic Dip Spread",
      "Roasted Garlic Marinara Sauce",
      "Dairy-Free Mozzarella shreds",
      "Parsely, for garnish"
    ],
    "directions": [
      "Prepare the shiitake mushrooms according to package instructions.",
      "Slice the baguette lengthwise and generously spread the garlic dip on each piece.",
      "Toast the baguette until it starts to crisp and brown.",
      "Add the cooked mushrooms to the bottom slice of bread and top with marinara and dairy-free mozzarella.",
      "Air fry or broil on high until cheese is melted.",
      "Garnish with parsley, close sandwich, and enjoy!"
    ],
    "notes": "Source: Instagram.com",
    "link": "https://www.instagram.com/reel/DCaQkFNytrh/?igsh=MW12a21jb3pyd3ppcw%3D%3D",
    "category": "",
    "imageUrl": "https://instagram.fmli1-1.fna.fbcdn.net/v/t51.2885-15/467108526_18476114833043998_6043460789861791912_n.jpg?stp=dst-jpg_e15_tt6&efg=eyJ2ZW5jb2RlX3RhZyI6ImltYWdlX3VybGdlbi43MjB4MTI4MC5zZHIuZjc1NzYxLmRlZmF1bHRfY292ZXJfZnJhbWUifQ&_nc_ht=instagram.fmli1-1.fna.fbcdn.net&_nc_cat=110&_nc_ohc=_dHLkAW2IwsQ7kNvgG7-Uy0&_nc_gid=6ebe5ff9e2024a34923f9f039988212c&edm=APs17CUBAAAA&ccb=7-5&ig_cache_key=MzUwMjE4NDUwODQ3OTQyOTM0NQ%3D%3D.3-ccb7-5&oh=00_AYDThOZeZEfHjb4CKQQnOaft6cYLkPWxgcHywaty0Zmlow&oe=67A32256&_nc_sid=10d13b",
    "isFavorite": false,
    "rating": 0,
    "cookCount": 0
  },
  {
    "name": "One Pan Asian Noodles",
    "ingredients": [
      "8 oz rice noodles",
      "1/2 block tofu cubed",
      "2 sliced bell peppers",
      "1 cup sliced shiitake mushrooms",
      "1 cup edamame",
      "2 cups chopped bok choy",
      "Sauce:",
      "16 oz water",
      "1/4 cup tamari or soy sauce",
      "1/4 cup teriyaki sauce",
      "1 tbsp chili garlic paste or sriracha",
      "1 tbsp toasted sesame oil",
      "Garnish:",
      "1 tbsp sesame seeds",
      "1 tbsp scallions"
    ],
    "directions": [
      "Pre heat the oven to 400F",
      "Pour and mix sauce ingredients in an oven safe casserole dish",
      "Add in the noodles, tofu, and vegetables. Make sure noodles are covered in sauce.",
      "Put in the oven for 20-25 minutes until sauce is absorbed and noodles are cooked!",
      "(Don't overcook it will get mushy!)",
      "Add garnish"
    ],
    "notes": "Can also be done in a skillet on the stove. \nVeggies, tofu, and sauce can be prepped ahead and stored separately. Add all ingredients to pan when cooking.\nSource: Healthy Girl Kitchen Instagram",
    "link": "",
    "category": "Dinner",
    "imageUrl": "",
    "isFavorite": false,
    "rating": 5,
    "cookCount": 0
  },
  {
    "name": "PB&J Protein Cookies",
    "ingredients": [
      "3 bananas",
      "2 cups oats",
      "2 cups organic @pbfit powdered peanut butter",
      "1 tbsp baking powder",
      "3/4 cup soy milk",
      "Pinch of salt",
      "1.5 cups frozen raspberries"
    ],
    "directions": [
      "\ud83c\udf4cMash your bananas in a large bowl then add in the rest of the ingredients (except for the raspberries)",
      "\ud83e\udd44 Mix to combine then fold in your raspberries.",
      "\ud83d\udd25 Divide into 6 cookies and bake at 400f for 15-18 minutes.",
      "\ud83e\udd5cOptionally you can also make a high protein PB drizzle by mixing extra PBfit with water \ud83e\udd24",
      "Store in the fridge for up to 6 days and enjoy \ud83e\udef6"
    ],
    "notes": "Source: Instagram.com",
    "link": "https://www.instagram.com/reel/DHgZ5QDxgFn/?igsh=ZXVxMWJvYTJwN2Iy",
    "category": "Sweets",
    "imageUrl": "https://instagram.fmli1-1.fna.fbcdn.net/v/t51.2885-15/485454161_18301048045209141_5601647327347852188_n.jpg?stp=dst-jpg_e35_p1080x1080_sh0.08_tt6&_nc_ht=instagram.fmli1-1.fna.fbcdn.net&_nc_cat=109&_nc_oc=Q6cZ2QFDJbv-4JZ7CVcezYiarBOJhhbLdnCPpqr8qj8p1eLKFLeoWhd9YxqZu6xjGUvmv38&_nc_ohc=aX6XfR48HGIQ7kNvgFRhIXF&_nc_gid=_NauEQUjMm5Pbs-z1Z--UA&edm=APU89FABAAAA&ccb=7-5&oh=00_AYFjEHArW66rM6v7xOmsP8NlviuStdbYUkGVlQkoJ6nPlw&oe=67E4C83A&_nc_sid=bc0c2c",
    "isFavorite": false,
    "rating": 0,
    "cookCount": 0
  },
  {
    "name": "Pot Sticker Stir Fry",
    "ingredients": [
      "1/2 onion diced",
      "4 oz sliced mushrooms",
      "2 carrots julienned",
      "Splash of veggie broth for saut\u00e9ing",
      "1 package tempeh cubed",
      "1 zucchini sliced",
      "2 cups broccoli florets",
      "3 tbsp teriyaki sauce mixed with 1/4 cup water or broth",
      "Sesame seeds and kimchi for serving"
    ],
    "directions": [],
    "notes": "",
    "link": "https://youtu.be/xah3Pf0nqMw?si=AZC0S49B0dp9bMLY",
    "category": "",
    "imageUrl": "https://img.youtube.com/vi/xah3Pf0nqMw/hqdefault.jpg",
    "isFavorite": false,
    "rating": 0,
    "cookCount": 0
  },
  {
    "name": "Sheet Pan Ghnocchi",
    "ingredients": [
      "Here\u2019s what you need:",
      "1 package vacuum sealed gnocchi",
      "1 package veggie sausage of choice, sliced (I used @fieldroast)",
      "1 pint cherry tomatoes, halved",
      "2 bell peppers, chopped",
      "2-3 tablespoons olive oil",
      "1/2 teaspoon each salt and pepper"
    ],
    "directions": [
      "Combine together in a sheet pan\u2014 roast at 350 for 20 minutes, stirring halfway through."
    ],
    "notes": "Source: Instagram.com",
    "link": "https://www.instagram.com/reel/DNtaNx_XpaY/?igsh=MWV2NTA1ejd1Z3J4cg%3D%3D",
    "category": "",
    "imageUrl": "https://scontent.cdninstagram.com/v/t51.82787-15/538965216_18324404743229981_4702749379286094391_n.jpg?stp=cmp1_dst-jpg_e35_s640x640_tt6&_nc_cat=100&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0xJUFMuYmVzdF9pbWFnZV91cmxnZW4uQzMifQ%3D%3D&_nc_ohc=gKyefGIxrgUQ7kNvwHNIsuH&_nc_oc=AdmWKJ_BIin-gYxxRRPt0TCbRiPHbdsUo11HvrGFyxQ2pgiMCzaYOK29Jyh5yiLWUcM&_nc_zt=23&_nc_ht=scontent.cdninstagram.com&_nc_gid=7voKp1VXSw9W21ALfjGj7w&oh=00_Afpo_C0B5N_fmuwj1BMWBYpJtCnL4RE8l2mMhJOv8aZdHA&oe=695FA383",
    "isFavorite": false,
    "rating": 0,
    "cookCount": 0
  },
  {
    "name": "Soy Curl Crumble Tacos",
    "ingredients": [
      "1 onion diced",
      "1 bell pepper diced",
      "4 oz mushrooms diced",
      "1/2 package soy curl taco crumbles soaked",
      "1/2 can black beans drained/ rinsed",
      "1/2 can black beans mashed",
      "8 siete almond flour tortillas",
      "Shredded cheese"
    ],
    "directions": [
      "Saut\u00e9 the onions, bell peppers and mushrooms together til softened. Add in the southwest seasoning, chili powder and adobo and stir. Add in the soaked pea crumbles and black beans and stir to combine. Add veggie broth and simmer til the pea crumbles are soft and chewy. Scoop about 1/4 cup of filling into tortilla, top with cheese and fold in half.",
      "Place on a baking sheet lined with parchment paper.",
      "Bake @375 for 14 mins flip halfway through."
    ],
    "notes": "",
    "link": "",
    "category": "",
    "imageUrl": "",
    "isFavorite": false,
    "rating": 0,
    "cookCount": 0
  },
  {
    "name": "Sriracha Noodles",
    "ingredients": [
      "2 bricks of the squiggly knife-cut style noodles (half a pack)",
      "1 block of sriracha tofu, cubed",
      "1 pack of vegetables with stir-fry sauce"
    ],
    "directions": [
      "Heat a medium pot and cook noodles according to package instructions.",
      "Add your vegetables and tofu in a large skillet and cook for about 5 minutes.",
      "Add in the stir-fry sauce and cook for another 2 minutes. Add in the cooked noodles and the sesame and soy sauce packet that came with the noodles.",
      "Mix through and serve!"
    ],
    "notes": "Source: Instagram.com",
    "link": "https://www.instagram.com/reel/C90ksl-SBeO/?igsh=emFhNGNpM3JxYnVt",
    "category": "",
    "imageUrl": "https://instagram.fmli1-1.fna.fbcdn.net/v/t51.29350-15/452633096_1403272011075597_2398284088503447884_n.jpg?stp=dst-jpg_e15_tt6&efg=eyJ2ZW5jb2RlX3RhZyI6ImltYWdlX3VybGdlbi43MjB4MTI4MC5zZHIuZjI5MzUwLmRlZmF1bHRfY292ZXJfZnJhbWUifQ&_nc_ht=instagram.fmli1-1.fna.fbcdn.net&_nc_cat=109&_nc_oc=Q6cZ2QFCtQWPrEo8duS28ckaGl3rm0w4I7BGYrs5qY0uuq4RGXGMfS0bspAeolCQGXW9e4o&_nc_ohc=04BW6aqPyhcQ7kNvgGbdvo7&_nc_gid=c6vyKjeYBnwYGUtARomyxA&edm=APs17CUBAAAA&ccb=7-5&ig_cache_key=MzQxOTUxOTQxMTE4NTc4NDcxOA%3D%3D.3-ccb7-5&oh=00_AYFZkSZHc1XP4FyerCjCeWI34ue_4ar4rcI8DqtJDmC0Ng&oe=67E62EEA&_nc_sid=10d13b",
    "isFavorite": false,
    "rating": 0,
    "cookCount": 0
  },
  {
    "name": "Super Seedy Pumpkin Pie Oatmeal! \ud83c\udf83",
    "ingredients": [
      "1 cup rolled oats.",
      "2 cups oat/almond milk.",
      "2 tablespoons chia seeds.",
      "2 tablespoons hemp seed.",
      "1/2 pumpkin puree.",
      "1 mashed banana.",
      "1 tsp vanilla extract.",
      "1/4 tsp cinnamon.",
      "1/8 tsp ginger.",
      "Pinch cardamon, nutmeg, ground cloves, salt"
    ],
    "directions": [
      "Here\u2019s how to make it \ud83d\udc49",
      "1\ufe0f\u20e3 Add 1 cup of rolled oats and 2 cups of your favorite milk (we used soy) to a saucepan and bring to a boil.",
      "2\ufe0f\u20e3 Once about half the liquid has been absorbed (~3-5 minutes), turn the heat to medium low and add 2 tablespoons chia seeds and 2 tablespoons hemp seeds and continue to cook until almost all the liquid has been absorbed (~2 minutes).",
      "3\ufe0f\u20e3 Add 1/2 cup pumpkin puree, 1 mashed banana, 1 tsp vanilla or maple extract, 1/4 tsp cinnamon, 1/8 tsp ginger, and a pinch of cardamom, nutmeg, ground cloves, and salt. Stir and continue to cook for another minute or two."
    ],
    "notes": "Source: Instagram.com",
    "link": "https://www.instagram.com/reel/CkbdGkQAfQp/?igsh=MXE2YnU4cjEzZ2dtYQ%3D%3D",
    "category": "",
    "imageUrl": "https://scontent.cdninstagram.com/v/t51.36329-15/313318690_648774066845311_1087133097840352044_n.jpg?stp=cmp1_dst-jpg_e35_s640x640_tt6&_nc_cat=102&ccb=7-5&_nc_sid=18de74&_nc_ohc=me97GTniIgMQ7kNvwFEuPqo&_nc_oc=AdnzSYSODOi1twVwIyMWMBTQDYhNSwunX7JIX9kzhbFhk3oRnUvp2Dvgi5jQBiYY8dw&_nc_zt=23&_nc_ht=scontent.cdninstagram.com&_nc_gid=4vnbxn_u8veeCtTKmafrfg&oh=00_AfGGLjdFedtoN9tv33O0gt_faZTSqxmIIs-VWcBzqpG1Ag&oe=681D5239",
    "isFavorite": false,
    "rating": 0,
    "cookCount": 0
  },
  {
    "name": "Thai Style Peanut Dressing",
    "ingredients": [
      "\u00bd cup Shredded Green Cabbage",
      "About 2 tablespoons vegan Tzatziki",
      "1 Block Super Firm Tofu",
      "Thai Style Peanut Dressing",
      "Olive Oil",
      "Salt & Pepper",
      "Green Onion Pancakes"
    ],
    "directions": [
      "Mix the shredded green cabbage and tzatziki until combined. Set aside in the fridge.",
      "Slice super firm tofu into \u00bd slabs and fry them on each side with salt and pepper until crispy.",
      "Toss the tofu into the peanut dressing and coat on both sides.",
      "Allow the green onion pancakes to defrost, and gently roll them out with a rolling pin until they are slightly thinner than normal.",
      "Add 2 slabs of tofu and a handful of the cabbage slaw to the pancake and fold in the sides completely, enclosing the filling.",
      "Air-fry the wrap at 375 degrees for about 15-20 minutes or until crispy.",
      "Allow to cool slightly, serve with additional peanut sauce, and enjoy!"
    ],
    "notes": "Source: Instagram.com",
    "link": "https://www.instagram.com/reel/DDLAFQSzMmQ/?igsh=ZzVveGZmMDFkdmxx",
    "category": "",
    "imageUrl": "https://scontent.cdninstagram.com/v/t51.75761-15/469389722_18479697202043998_1244488128777864909_n.jpg?stp=cmp1_dst-jpg_e35_s640x640_tt6&_nc_cat=106&ccb=1-7&_nc_sid=18de74&_nc_ohc=pYBquYydtEgQ7kNvwHCm9qi&_nc_oc=Adk16vZc1OJDbDT68Sdl7lZFP23OlHR36U_MZNmJdodKt0Fs2d-LVGNfAJP2r6WUg4s&_nc_zt=23&_nc_ht=scontent.cdninstagram.com&_nc_gid=ErCvqILRIHsiUi79_y89KA&oh=00_AfMOG0BMXN0O9LELBtOUSUgoTXJmKn9x2bkOqJZ0i5AnRA&oe=684BEE2E",
    "isFavorite": false,
    "rating": 0,
    "cookCount": 0
  },
  {
    "name": "Ultimate Vegan Chili",
    "ingredients": [
      "Meaty Tofu Crumbles",
      "2 tablespoons soy sauce *tamari for gluten free",
      "2 tablespoons nutritional yeast",
      "2 teaspoons chili powder",
      "1 teaspoon smoked paprika",
      "14 ounce block firm tofu",
      "Chili",
      "2 tablespoons olive oil",
      "1 medium sweet onion, diced",
      "3-4 cloves garlic, minced",
      "(2) 28-oz cans crushed tomatoes",
      "(2) 15-oz cans black beans, drained and rinsed",
      "(1) 15-oz can kidney beans, drained and rinsed",
      "1 cup water",
      "3 tablespoons chili powder",
      "2 teaspoons ground cumin",
      "1 tablespoon pure maple syrup",
      "1 tablespoon cocoa powder",
      "1 teaspoon smoked paprika",
      "1/4 teaspoon cayenne pepper",
      "1 teaspoon salt, or to taste"
    ],
    "directions": [
      "Make the tofu crumbles",
      "Preheat the oven to 350 degrees F and line a baking sheet with parchment paper.",
      "In a large bowl, mix together the soy sauce, nutritional yeast, chili powder and smoked paprika. It will be pasty. Now crumble the tofu into the bowl with your hands, and mix together using a large spoon until well combined with the paste.",
      "Spread the tofu mixture evenly in the pan. Place in the oven and bake for 30 minutes, stirring the tofu halfway through. Once the tofu is in the oven, start the chili.",
      "Prepare chili on the stovetop",
      "In a large pot over medium heat, add the olive oil. Add the chopped onion and saut\u00e9 3-4 minutes until translucent. Add in the garlic and cook 1 more minute, stirring constantly.",
      "Now add all the rest of the chili ingredients, except the tofu, and stir to combine. Bring to a boil, then lower the heat and simmer for about 20 minutes, until the tofu crumbles are done baking.",
      "If a thicker consistency is desired, use an immersion blender and blend just a few times. Do this before you add the tofu.",
      "Once the tofu crumbles are done, stir them into the pot. All done! Serve with vegan sour cream, cornbread, tortilla chips, cilantro, tomatoes, hot sauce, vegan cheese shreds and chives, if desired."
    ],
    "notes": "Use vegan beef instead: May omit the tofu crumbles if desired, or replace them with vegan beef crumbles (such as Gardein brand or Beyond Meat). Saut\u00e9 the ground meat with the onion, then add the garlic and continue with the recipe. Or simply add some vegetables instead, like frozen corn, red bell peppers, sweet potatoes, carrots or zucchini. Or add a cup of uncooked quinoa when you add the beans.\n\nMay substitute diced tomatoes for the crushed tomatoes if desired for more texture.\n\nLeftovers: This chili will keep in the fridge for about 4-5 days, and also freezes well.\n\nInstant Pot version: Use the saut\u00e9 feature and cook your onion and garlic, then add the rest of the ingredients (except the tofu, bake that in the oven like normal). Secure the lid and cook at high pressure for 8 minutes. Stir in the tofu crumbles and serve.\n\nSlow cooker version: Add all of the ingredients (except the tofu) and cook on high for 2-3 hours or low for 4-5 hours. Stir in the tofu crumbles about 30 minutes before it\u2019s done cooking.\nServings: Servings: 6 servings | Prep: 10 mins | Cook: 30 mins | Source: noracooks.com",
    "link": "https://www.noracooks.com/ultimate-vegan-chili/",
    "category": "Dinner",
    "imageUrl": "https://www.noracooks.com/wp-content/uploads/2023/04/vegan-chili-5-150x218.jpg",
    "isFavorite": false,
    "rating": 4,
    "cookCount": 0
  },
  {
    "name": "VEGAN \u201cCHEESESTEAK\u201d PASTA SKILLET",
    "ingredients": [
      "1 medium yellow onion, sliced into strips",
      "1 red bell pepper, sliced into strips",
      "1 green bell pepper, sliced into strips",
      "1 \u2013 [ 14 oz. can ] brown lentils, drained and rinsed *",
      "Sauce Ingredients:",
      "\u00bc cup raw cashews *",
      "2 teaspoons tahini *",
      "1 teaspoon Dijon mustard *",
      "\u00bc cup + 2 Tablespoons water",
      "2 Tablespoons distilled white vinegar",
      "1 Tablespoon reduced-sodium tamari *",
      "\u00bc cup low-sodium vegetable broth *",
      "3 Tablespoons nutritional yeast",
      "2 Tablespoons dried minced onions",
      "1 teaspoon onion powder",
      "1 teaspoon garlic powder",
      "\u00bc to \u00bd + big pinch teaspoon sea salt (+/-) *",
      "Other Ingredients",
      "8 oz. to 10 oz. fusilli pasta (or pasta of choice) *",
      "Optional Toppings:",
      "Freshly chopped parsley"
    ],
    "directions": [
      "Pasta Boil Instructions",
      "Fill a large stock pot full of water. Add some sea salt to the water. Bring the water to a boil then add the pasta. Stir occasionally to prevent sticking. Boil the pasta according to package directions, drain, rinse well with cold water, and set aside until ready to use.",
      "Place the cashews into a small bowl, cover with boiling water for 10 minutes, then drain and place the softened cashews into a high-speed blender with all the remaining Sauce Ingredients. Blend on high until smooth and emulsified. Set aside until ready to use.",
      "In the meantime, in a large ceramic/enamel lined skillet or similar nonstick skillet, add the sliced onions and bell peppers, saut\u00e9 over medium-high heat for 7 to 11 minutes until the onions and peppers are tender. (If needed to prevent sticking or burning, add a splash of vegetable broth or water).",
      "Once tender, add the lentils, cook for a few minutes, then add Sauce Mixture, and the cooked pasta, still well, simmer for several minutes on low heat until everything is thoroughly heated through. Remove from the stove, cover with a tight-fitting lid and allow to sit for 5 minutes. Serve immediately with freshly chopped parsley."
    ],
    "notes": "*TIPS FOR SUCCESS:\n\nAmount of Pasta: While it is very tempting to use a full pound of pasta, we strongly recommend using the ingredient amount listed, 8 oz. up to 10 oz. If you use more than the listed amount, you could end up with a drier pasta dish as the pasta really drinks up the sauce. If you enjoy a really saucy dish, use 8 oz.\n\nTenderness of the Bell Peppers and Onions: Do not advance to the next step until the bell peppers and onions are saut\u00e9ed to your desired level of tenderness as they will not cook much more after that point.\n\nCashew Based Sauces: Cashew based sauces tend to thicken quickly once they are in the skillet and when they cool down. If needed, add a splash of water or broth (or a little distilled white vinegar) to loosen it up.\nServings: Yield: 4 servings | Prep: 15 minutes | Cook: 15 minutes | Source: Monkeyandmekitchenadventures.com",
    "link": "https://monkeyandmekitchenadventures.com/vegan-cheesesteak-pasta-skillet/",
    "category": "Pasta",
    "imageUrl": "https://monkeyandmekitchenadventures.com/wp-content/uploads/2020/12/Vegan-Cheesesteak-Pasta-Skillet_04-1365x2048.jpg",
    "isFavorite": false,
    "rating": 4,
    "cookCount": 0
  },
  {
    "name": "Vegan French Toast Casserole",
    "ingredients": [
      "1x 2x 3x",
      "1 day old large loaf (14-16 ounces) french or sourdough bread* cut into 1 inch cubes (about 10 cups)",
      "12 ounces silken tofu",
      "(1) 13.5-ounce can full fat coconut milk",
      "2 tablespoons cornstarch",
      "1/2 cup granulated sugar",
      "1 tablespoon pure vanilla extract",
      "1 teaspoon ground cinnamon",
      "1/4 teaspoon salt",
      "Topping",
      "1/2 cup brown sugar",
      "1/4 cup all purpose flour",
      "1 teaspoon ground cinnamon",
      "3 tablespoons vegan butter, cold"
    ],
    "directions": [
      "Prepare the bread: Cut the bread into 1 inch cubes. I do this by first slicing the loaf, then cutting into smaller cubes. Lightly grease a 9 by 13 inch casserole dish, and add the bread cubes to it.",
      "Make the custard: In a blender, add the silken tofu (drained of water if needed), coconut milk, cornstarch, sugar, vanilla, cinnamon and salt. Blend until smooth.",
      "Pour the custard over the bread cubes. Using your hands, press the bread down into the custard a few times, until the bread is soaked in it. Cover and place in the refrigerator for 8-12 hours. You can bake it immediately if you prefer.",
      "In the morning, preheat the oven to 350 degrees F.",
      "Make the topping: In a small bowl, combine the brown sugar, flour and cinnamon. Then cut the vegan butter in with a fork or your fingers. Sprinkle this over the top of the casserole.",
      "Bake, uncovered, for 40-50 minutes, until golden brown on top and cooked throughout.",
      "Sprinkle with a dusting of powdered sugar and serve with warm, pure maple syrup. Enjoy!"
    ],
    "notes": "You MUST use day old, dried out bread for the casserole. If you use moist, fresh bread, you will have a soggy casserole and it will not taste good! Sometimes you can even buy day old bread at your grocery store, discounted. If you only have fresh, cut it up and let it sit at room temperature, uncovered for a few hours to dry out.\n\nYou can use mori-nu silken tofu, or the silken tofu packed in water. Simply drain all the water you can from the packaging before using.\nServings: Serving: 1 | Prep: 10 mins | Cook: 50 mins | Source: Noracooks.com",
    "link": "https://www.noracooks.com/vegan-french-toast-casserole/#wprm-recipe-container-4961",
    "category": "",
    "imageUrl": "https://www.noracooks.com/wp-content/uploads/2019/05/IMG_4785-500x500.jpg",
    "isFavorite": false,
    "rating": 0,
    "cookCount": 0
  },
  {
    "name": "Vegan Soy Curl Fajitas",
    "ingredients": [
      "Base Ingredients:",
      "\u00bd red bell pepper, thinly sliced",
      "\u00bd green bell pepper, thinly sliced",
      "1 large yellow onion, thinly sliced",
      "1 Tablespoon minced garlic",
      "1 teaspoon GF flour (or flour of choice) *",
      "1 Tablespoon tomato paste",
      "1 Tablespoon reduced-sodium tamari *",
      "1 Tablespoon + 1 teaspoon lime juice",
      "2 Tablespoon vegetable broth *",
      "3 Tablespoons water",
      "Spice/Herb Ingredients:",
      "1 teaspoon onion powder",
      "1 teaspoon garlic powder",
      "1 Tablespoon dried minced onions",
      "1 \u00bd teaspoon chili powder",
      "\u00bd teaspoon cumin",
      "\u00bd teaspoon smoked paprika",
      "\u00bd teaspoon Mexican oregano (or regular oregano)",
      "\u00bd teaspoon sea salt (+/-) *",
      "1/8 teaspoon black pepper",
      "1/8 to \u00bc teaspoon cayenne pepper (+/-)",
      "Other Ingredients:",
      "2 cups soy curls *",
      "Serving Ideas:",
      "Flour tortillas",
      "Steamed brown rice (rice of choice)",
      "Tomato wedges",
      "Chopped avocadoes",
      "Freshly chopped cilantro"
    ],
    "directions": [
      "Hydrate the soy curls according to package directions, then squeeze out the excess water before placing them in the skillet in Step 5.",
      "Place all the Spice/Herb Ingredients into a small bowl, whisk, set aside.",
      "In an enamel/ceramic lined Dutch oven, skillet or similar stock pot, add the sliced bell peppers and onions, saut\u00e9 over medium-high heat to soften, approximately 8 to 10 minutes. Add a splash of water to prevent sticking and burning.",
      "Then add the minced garlic and saut\u00e9 for a few minutes, then add the tomato paste and flour, saut\u00e9 for one minute. Next add the Spice/Herb mix, saut\u00e9 for one minute to allow the spices to release their fragrance; then add all the remaining Base Ingredients, stir to combine.",
      "Add the hydrated and squeezed soy curls and stir thoroughly to get them all coated well with the mixture. Heat for 2 to 3 minutes or until the soy curls are heated through. Taste test, adjust spices, if needed to reach the desired flavor.",
      "Remove from heat, serve over rice with your favorite toppings or with flour tortillas as a fajita."
    ],
    "notes": "Servings: Yield: 9 tacos | Prep: 5 minutes | Cook: 15 minutes | Source: monkeyandmekitchenadventures.com",
    "link": "https://monkeyandmekitchenadventures.com/vegan-soy-curl-fajitas/",
    "category": "Sandwiches",
    "imageUrl": "https://monkeyandmekitchenadventures.com/wp-content/uploads/2020/03/Vegan-Soy-Curl-Fajitas-Image_11-1229x1536.jpg",
    "isFavorite": false,
    "rating": 0,
    "cookCount": 0
  },
  {
    "name": "Vegan Spinach & Artichoke Casserole",
    "ingredients": [
      "1 13.5-ounce can of full-fat coconut milk (1 3/4 cup or 400 ml)",
      "1/2 cup (120 ml) vegetable broth (vegetable or vegan chicken-flavored)",
      "Juice of 1 lemon (3 to 4 tablespoons)",
      "2 tablespoons nutritional yeast",
      "1/2 tsp sea salt",
      "2 15.5-ounce (440 g) cans of Great Northern, Navy, or Cannelini beans (~2.5 cups cooked beans)",
      "8.5 ounces (240 g) artichoke hearts, roughly chopped (1 can)",
      "1 10-ounce (280 g) bag of frozen spinach, thawed and drained*",
      "1 large shallot, diced",
      "3 cloves garlic, minced",
      "1 cup dry white rice*",
      "Optional: vegan parmesan or other dairy-free cheese, for serving"
    ],
    "directions": [
      "Preheat the oven to 375F and set a 9\u00d713\u2033 or similar pan.",
      "Prepare: Add the coconut milk, broth, lemon juice, nutritional yeast, and salt to a medium pot and bring to a boil over high heat. While the liquid heats, add the beans, artichoke hearts, drained spinach, shallot, garlic, and uncooked rice to the casserole dish. Mix them around and spread evenly across the bottom of the casserole with a spatula.",
      "Bake: Once the liquid comes to a boil, carefully pour it over the casserole and cover with a layer of parchment paper (optional) followed by a layer of aluminum foil (not optional). Place in the middle rack of the oven and bake for 45 minutes.",
      "Serve:Remove the casserole from the oven and let sit for 5 minutes, then uncover. Divide into serving bowls and top with vegan parmesan, or as desired. Leftovers will last in the fridge for up to 5 days, or can be frozen for up to 2 months."
    ],
    "notes": "If you have a coconut allergy you can replace it with another thick & creamy dairy-free milk, such as oat milk. I also think you could blend 1/2 cup of vegan cream cheese with 1 1/4 cups of water for another alternative, but I haven\u2019t tested this myself.\n\nDraining Spinach: I like to put the package of frozen spinach into my fridge the day before I make this. You can also soak the spinach in hot water. Make sure to drain your spinach thoroughly and get as much liquid out as possible; I recommend placing it in a fine metal strainer and pressing it into the strainer, as well as using your hands to squeeze fistfuls of the spinach to get out any extra liquid.\n\nWhite vs Brown Rice: white rice and brown rice require different cooking times, so you cannot swap them 1:1. If you want to make this recipe with brown rice, keep all ingredients and measurements the same, but bake the casserole at 400F for 60 minutes instead.\n\nWant it Cheesy? For an extra cheesy casserole, sprinkle up to 1 cup of dairy-free shredded cheese on top of the casserole after you mix the liquid in; cover and bake according to the recipe instructions.\nServings: Serves 4 | Prep: 10 min | Cook: 10 minutes | Source: Frommybowl.com",
    "link": "https://frommybowl.com/vegan-spinach-artichoke-casserole/",
    "category": "",
    "imageUrl": "https://frommybowl.com/wp-content/uploads/2020/05/Vegan_Spinach_Artichoke_Casserole_White_Beans_DumpandBake_FromMyBowl-5.jpg",
    "isFavorite": false,
    "rating": 0,
    "cookCount": 0
  },
  {
    "name": "WEEK OF EASY HEALTHY DINNER RECIPE IDEAS! Part 2! - YouTube",
    "ingredients": [
      "Broccoli soup:",
      "1 onion diced",
      "4 oz mushrooms diced",
      "2 carrots diced",
      "2 cloves garlic minced",
      "12 oz broccoli chopped small",
      "4 cups veggie broth",
      "1/4 cup nutritional yeast",
      "1/2 tsp turmeric",
      "1/2 tsp dried thyme",
      "Fresh black pepper",
      "2 tsp liquid aminos or salt to taste",
      "1 can white kidney beans drained/ rinsed",
      "1/2 cup nuts- I used a mix of hemp sunflower and cashew",
      "1 cup water",
      "1 tbsp arrowroot plus 1 tbsp water",
      "Dumpling veggie stir fry:",
      "1/2 onion diced",
      "4 oz sliced mushrooms",
      "2 carrots julienned",
      "Splash of veggie broth for saut\u00e9ing",
      "1 package tempeh cubed",
      "1 zucchini sliced",
      "2 cups broccoli florets",
      "3 tbsp teriyaki sauce mixed with 1/4 cup water or broth",
      "Sesame seeds and kimchi for serving",
      "Ravioli primavera",
      "1/2 onion diced",
      "4 oz mushrooms sliced",
      "1 cup cherry tomatoes sliced",
      "4 cloves minced garlic",
      "1 zucchini sliced",
      "Handful of broccoli florets",
      "1 tsp Italian seasoning",
      "Crushed red pepper flakes",
      "Garlic salt to taste",
      "1 package cashew/ spinach ravioli from TJ",
      "1 cup reserved pasta water",
      "For the white bean sauce:",
      "1/2 cup white beans drained and rinsed",
      "1/4 cup hemp seeds soaked",
      "Garlic powder",
      "1/2 cup water",
      "Crunchy pea protein tacos",
      "1 onion diced",
      "1 bell pepper diced",
      "4 oz mushrooms diced",
      "1 tbsp mrs dash southwest chipotle",
      "2 tsp chili powder",
      "1/4 tsp adobo seasoning",
      "1 cup textured pea protein soaked in veg broth",
      "1/2 cup veggie broth",
      "1/2 can black beans drained/ rinsed",
      "1/2 can black beans mashed",
      "8 siete almond flour tortillas",
      "Shredded cheese",
      "Avocado sauce:",
      "1 avocado",
      "1/2 zucchini",
      "Juice of 1 lime",
      "Pinch of garlic salt",
      "1/2 cup water",
      "Broccoli kale pesto pasta:",
      "Handful of kale",
      "1 cup broccoli florets",
      "Pesto ingredients:",
      "1/2 cup packed basil",
      "2 garlic cloves",
      "1 lemon juiced plus the zest",
      "3 tbsp nutritional yeast",
      "Salt and pepper to taste",
      "3/4 cup nuts/ seeds- I used 1/4 cup each of hemp seeds, sunflower seeds and cashews soaked in boiling water for 10 mins",
      "Pasta",
      "14 oz Lentil or whole wheat pasta"
    ],
    "directions": [
      "Saut\u00e9 the onion, mushrooms and tomatoes in veggie broth and seasonings til the tomatoes are soft. Add in the zucchini and broccoli and cover to steam the veggies. In the meantime boil the ravioli according to directions on the package. Drain and add to the veggies. Blend up the ingredients for the white bean sauce and pour the sauce into the veggies/ ravioli. Gently mix everything together. Season with salt and pepper to your taste. Add reserved pasta water to thin the sauce out if you wish.",
      "Saut\u00e9 the onions, bell peppers and mushrooms together til softened. Add in the southwest seasoning, chili powder and adobo and stir. Add in the soaked pea crumbles and black beans and stir to combine. Add veggie broth and simmer til the pea crumbles are soft and chewy. Scoop about 1/4 cup of filling into tortilla, top with cheese and fold in half. Place on a baking sheet lined with parchment paper.",
      "Bake @375 for 14 mins flip halfway through. Serve with salsa and avocado sauce.",
      "Boil a big pot of water on the stove. Blanch the kale and broccoli for 90 seconds. Take it out and add the kale and broccoli to a blender or food processor with the rest of the pesto ingredients and blend with 1/2 cup water. In the mean time boil the pasta according to the directions on the package. Save 1 cup of pasta water and drain the pasta. Add the pasta back to the pot with the pesto and mix. Add the pasta water slowly to get the consistency you like. Season with salt and pepper to taste.",
      "Add sun dried tomatoes and vegan cheese at the end. Olives would also be good to add in!"
    ],
    "notes": "Source: M.youtube.com",
    "link": "https://m.youtube.com/watch?v=xah3Pf0nqMw",
    "category": "",
    "imageUrl": "https://i.ytimg.com/vi/xah3Pf0nqMw/maxresdefault.jpg",
    "isFavorite": false,
    "rating": 0,
    "cookCount": 0
  },
  {
    "name": "Whole Wheat Fluffy Vegan Pancakes",
    "ingredients": [
      "1X 2X 3X",
      "1 cup whole wheat flour, 120 g",
      "1 tbsp baking powder, 12 g",
      "1/2 tsp sea salt",
      "1 cup unsweetened almond milk, 250 ml",
      "2 tbsp pure maple syrup, 30 ml",
      "1/2 tsp cinnamon, optional",
      "1 tsp pure vanilla extract, optional, 5 ml"
    ],
    "directions": [
      "Mix the dry ingredients together in a mixing bowl.",
      "I like to use a fork or whisk to help break up any lumps of flour and help thoroughly distribute the baking powder and salt. This is important for a fluffy result!",
      "Start heating a non-stick skillet, pancake griddle or crepe pan over medium heat. Add your liquid to the dry ingredients and gently fold until all the flour is wetted.",
      "The batter will be quite thick and almost foam-like, but still pourable. This is perfect and means the baking powder is working.",
      "Quick Tip: Let the batter rest for 5-10 minutes while you wait for the cooking surface to heat. This is key for fluffiness.",
      "Once the pan is hot, use a bit of non-stick cooking spray, if needed, then add approximately 1/3 cup portions of the batter to the pan.",
      "Let them cook until the edges appear dry, firm and golden brown, and small bubbles are starting to appear in the batter. This should take about 4-5 minutes.",
      "Flip and cook for another 30-90 seconds until cooked through and brown on both sides.",
      "Repeat until you\u2019ve used up the remaining batter. If you like, you can keep them warm in the oven at a low temperature until you\u2019re ready to serve.",
      "Notes and Tips",
      "For Vegan Buttermilk Pancakes: For a slightly tangy buttermilk flavour and a bit more rise to your pancakes, you can add 1-2 tsp of lemon juice, apple cider vinegar or white vinegar to the non-dairy milk and let it sit for 2-3 minutes before adding it to the batter.",
      "Mix together the whole wheat flour, baking powder, sea salt and cinnamon (if using) in medium mixing bowl using a fork or whisk to help break up any lumps of flour and distribute the baking powder and salt.",
      "Add the wet ingredients (non-dairy milk and maple syrup) and gently mix until all the flour has been mixed in. The batter will be thick and slightly lumpy.",
      "Let the batter rest for at least 5 minutes while you heat a nonstick skillet or griddle over medium heat.",
      "If needed, lightly oil the pan with coconut oil or olive oil or spray with a light coating of non-stick cooking spray, then scoop approximately 1/3 cup portions of the batter onto the pan. Cook the pancakes until the edges look dry, firm and golden brown and bubbles are appearing, then flip and cook for another 30-90 seconds until thick, fluffy and browned on both sides.",
      "Repeat with the remaining batter then serve right away with your favourite pancake toppings like fresh fruit and maple syrup."
    ],
    "notes": "Please note the conversions do not adjust if you double or triple the recipe so please make sure to calculate those manually if you increase the recipe.\n\nSweetener: Maple syrup can be substituted with your choice of sweetener such as coconut sugar, cane sugar, brown sugar or for sugar-free pancakes, stevia, monk fruit sweetener or erythritol.\n\nLiquid: Almond milk can be substituted with any non-dairy milk (except canned coconut milk) or water.\n\nFor Buttermilk Pancakes: Use all-purpose flour instead of whole wheat flour and add 2 tsp lemon juice, apple cider vinegar or white vinegar to the milk and let sit for a few minutes before adding to the batter.\n\nFor best results, make sure you active baking powder. If you\u2019re unsure if your baking powder is still good, you can test it by by mixing 1 teaspoon of baking powder with 1/3 cup hot water. If the baking powder is fresh, the mixture should fizz.\n\nAdd-Ins: Try mixing up to 1/2 cup fresh blueberries or 4 tbsp vegan chocolate chips into the batter or dropping a few onto each pancake after you\u2019ve added the batter to the pan.\nServings: Servings: 2 servings | Prep: 10 mins | Cook: 5 mins | Source: Runningonrealfood.com",
    "link": "https://runningonrealfood.com/whole-wheat-fluffy-vegan-pancakes/#wprm-recipe-container-11173",
    "category": "Breakfast",
    "imageUrl": "https://runningonrealfood.com/wp-content/uploads/2021/10/Easy-Vegan-Whole-Wheat-Fluffy-Pancakes-Recipe.jpg",
    "isFavorite": false,
    "rating": 4,
    "cookCount": 0
  },
  {
    "name": "Marry Me Creamy Tofu Dump & Bake",
    "ingredients": [
      "INGREDIENTS \u2728",
      "2 tbsp olive oil",
      "2 tbsp tomato paste",
      "2 cloves garlic, minced",
      "1 tbsp Italian seasoning",
      "1 tsp dried oregano",
      "1 tsp onion powder",
      "1 tsp paprika",
      "\u00bd cup sun-dried tomatoes, chopped",
      "1 cup zucchini/bell pepper, chopped",
      "1 block extra-firm tofu, cubed",
      "4 cups regular/gluten-free pasta (penne, rigatoni, or macaroni)",
      "2\u00bd cups vegetable broth",
      "1 can coconut milk",
      "2 handfuls baby spinach",
      "Salt & pepper, to taste",
      "1 cup vegan mozzarella (optional but amazing)",
      "1 tsp chili flakes (optional)",
      "\u2e3b"
    ],
    "directions": [
      "DIRECTIONS \ud83d\udc69\u200d\ud83c\udf73",
      "Preheat oven to 400\u00b0F (200\u00b0C).",
      "Add everything except the spinach and vegan mozzarella to a large baking dish. Stir well so the pasta and tofu are fully coated.",
      "Cover tightly with foil/lid and bake for 35\u201345 minutes, until the pasta is tender and most of the liquid is absorbed.",
      "Remove from the oven, stir in the spinach, and sprinkle the vegan mozzarella on top.",
      "Return to the oven uncovered for 5\u201310 minutes, until golden and bubbly. Enjoy!!! \ud83d\ude09"
    ],
    "notes": "Source: Instagram.com",
    "link": "https://www.instagram.com/reel/DSoHKXej2nt/?igsh=MXN3OWltZDFwbW5q",
    "category": "",
    "imageUrl": "https://scontent.cdninstagram.com/v/t51.71878-15/605150216_1404275831338984_1688788686044873245_n.jpg?stp=cmp1_dst-jpg_e35_s640x640_tt6&_nc_cat=107&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0xJUFMuYmVzdF9pbWFnZV91cmxnZW4uQzMifQ%3D%3D&_nc_ohc=ImOcz7dQB2sQ7kNvwGzeYqG&_nc_oc=AdmW9_aCnQzsV7ZurZjHIPaOYL3jA0yWD1XMc8IpzcjiEI4IACW4sV8iiaf-u3qgShU&_nc_zt=23&_nc_ht=scontent.cdninstagram.com&_nc_gid=9nLJteG5ZYjAccdpDeUNEQ&oh=00_AfopxbUoKRF-Rk62b8dB9pXr94kzgmQ0l0JqRJoBdxl4XA&oe=696F66E4",
    "isFavorite": false,
    "rating": 0,
    "cookCount": 0
  }
];
